name: edu_ui_kit
description: "A flexible and beautiful UI kit for education apps with Material Design 3 support"
version: 0.0.1
homepage: https://github.com/mixin27/edu_ui_kit

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  file_picker: ^10.3.7

  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
